name: ngh09_ui_kit_example
description: Example app demonstrating ngh09_ui_kit.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  ngh09_ui_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
